### ISSUE TITLE
Please make it available in a single .py file again

### ISSUE THREAD

**Issue by l00tzOMG** [Irrational-Encoding-Wizardry/lvsfunc#11]
For the people who use portable VapourSynth it is much easier to use a single .py file. Messing with pip is rather a horror with embedded (portable) python.

If possible please make a single lvsfunc.py (like it was earlier) for the people, who use portable versions.

Thank you in advance,

**Comment by LightArrowsEXE** [comment]
You should be able to just stick the `lvsfunc` directory in your `site-packages` and it'll work.

**Comment by FichteFoll** [comment]
What embedded environment are you talking about that you can't properly use pip in? Regardless, even if you can't use pip, you can still just download the folder, as Light said.

**Comment by l00tzOMG** [comment]
> You should be able to just stick the `lvsfunc` directory in your `site-packages` and it'll work, portable or not.

Seems to be working, thank you.



> What embedded environment are you talking about that you can't properly use pip in? Regardless, even if you can't use pip, you can still just download the folder, as Light said.
> 
> And, what makes this even more confusing, how did you use pip for this before? It's not on pypi and doesn't have any packaging meta information.

Standard portable python. Of course, you can install pip, but the PATH is not set and using it is a pain-in-the-ass. The reason to use this version is that if you have a complete portable VS package and you wish to use the same on 10+ computers, you don't want to bother with installing and setting the PATH, etc.
