### ISSUE TITLE
mask.py get_mask seems to be broken

### ISSUE THREAD

**Issue by Selur** [Irrational-Encoding-Wizardry/lvsfunc#143]
https://lvsfunc.encode.moe/en/latest/submodules/mask.html#lvsfunc.mask.BoundingBox states 
`ref (VideoNode) – Reference clip for format, resolution, and length.`
but looking at the code
https://github.com/Irrational-Encoding-Wizardry/lvsfunc/blob/34660f524a121824011d2c3d33fc3ba8f556f2f9/lvsfunc/mask.py#L350
especially
`mask: vs.VideoNode = core.std.BlankClip(ref, color=white, length=1, format=mask_fmt.id)`
https://github.com/Irrational-Encoding-Wizardry/lvsfunc/blob/34660f524a121824011d2c3d33fc3ba8f556f2f9/lvsfunc/mask.py#L367
seem wrong since the BlankClip only returns one frame, from the looks of it 'length=1' is the issue.
so  something like
`mask_d = lvs.mask.BoundingBox((0, 785), (665, 294)).get_mask(clip)`
only returns a clip with one frame not clip.num_frames.
so the solution should be to delete ', length=1'

**Comment by LightArrowsEXE** [comment]
Thanks. Can you elaborate on the "broken" part in the title? As far as I understood it, if the mask clip doesn't match the given clips in `MaskedMerge`, it will simply use the last frame of the mask clip for the remaining frames. Does the old code actually break anything relevant?

**Comment by Selur** [comment]
Used the `mask_d = lvs.mask.BoundingBox((0, 785), (665, 294)).get_mask(clip)` and ended with a clip that is one frame long instead of the length of the clip (~2hr @23.97fps).
Problem there is:
a. the documentation states something different
b. when I use:
```
mask_d = lvs.mask.BoundingBox((0, 785), (665, 294)).get_mask(clip )
mask_d = core.std.InvertMask(mask_d)
mask_e = jvs.flat_mask(clip , radius=5, thr=5, use_gauss=False)
mask_m = core.std.Expr([mask_d, mask_e], 'x y +')
shrp = core.warp.AWarpSharp2(clip, thresh=200, blur=2, depth=32, planes=[1, 2])
filteredClip = core.minideen.MiniDeen( shrp, radius=[4, 1, 1], threshold=[10, 10, 10])
clip = core.std.MaskedMerge(clip , filteredClip, mask_m)
```
Problem here is that mask_m only is one frame long which is the bounding box merged with the first frame of clip and that mask is applied to the first the whole clip, which is in no way what is expexted. So yes, at least for me it breaks stuff. (+ the documentation if wrong)

**Comment by LightArrowsEXE** [comment]
Gotcha. Well, now it properly returns the full-length clip, so that shouldn't be an issue anymore.
