### ISSUE TITLE
I found scale.py is removed but the doc still had

### ISSUE THREAD

**Issue by ted423** [Irrational-Encoding-Wizardry/lvsfunc#154]
https://lvsfunc.encode.moe/en/latest/submodules/scale.html#

Could let me know why remove this?

about ssim_downsample which one would you currently recommend using

**Comment by ted423** [comment]
Sorry ,It seems that lvsfunc.encode.moe has not been updated

**Comment by Setsugennoao** [comment]
It was moved to [vsscale](https://github.com/Irrational-Encoding-Wizardry/vs-scale).

`SSIM`, `ssim_downsample` can be found [here](https://github.com/Irrational-Encoding-Wizardry/vs-scale/blob/master/vsscale/scale.py).

I recommend doing `pip install vsiew`

**Comment by LightArrowsEXE** [comment]
Documentation will be fixed and updated once I have time to look at it.

**Comment by ted423** [comment]
Thanks a lot
