### ISSUE TITLE
Implement BM3DCUDA

### ISSUE THREAD

**Issue by NSQY** [Irrational-Encoding-Wizardry/lvsfunc#57]
https://github.com/WolframRhodium/VapourSynth-BM3DCUDA

The cuda implementation is quite fast:
Linux 5.12.6: 3900X, GTX 1080, Nv 465.31, cuda 11.3.0-2

> clip = core.std.BlankClip(width=1920, height=1080, format=vs.YUV444PS, color=[0.5,0,0], length=1000)
gpu = core.bm3dcuda.BM3D(clip, fast=True).set_output()

Output 1000 frames in 11.08 seconds (90.22 fps)

> clip = core.std.BlankClip(width=1920, height=1080, format=vs.YUV444PS, color=[0.5,0,0], length=1000)
gpu = core.bm3dcuda.BM3D(clip, fast=False).set_output()

Output 1000 frames in 42.47 seconds (23.55 fps)

**Comment by LightArrowsEXE** [comment]
lvsfunc's `denoise` submodule will soon be deprecated by another module. As such, I'm closing this issue.
