### ISSUE TITLE
Old function adoption list/requests

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/lvsfunc#74]
This issue will mark the list of older functions I plan on adopting as well as requested filters.
These will mainly be unmaintained functions from old *funcs or random gists.
I'm not necessarily planning to rewrite most of them, but I do plan on making sure they're at least R55 compliant, and will hopefully remain compliant with future VapourSynth API changes.

This is also the place to go to to request AVS ports.

Currently eyeing the following functions:

- [ ] Zastin's morpho deband function (Not publicised outside of discord, or if it was it's lost)
- [x] ~~BasedAA (Need to figure out why it breaks on certain setups before further plans are made)~~ Added, see [commit](https://github.com/Irrational-Encoding-Wizardry/lvsfunc/commit/a00ad4fec8540a02621e2d7d8009dd012ef1d05a).
- [ ] [RemoveDirt](https://github.com/kidaa/aur/blob/974ca1e3f0c741a0df2ad29c5d7ee3dc8e32d92c/vapoursynth-plugin-removedirtvs-git/removedirtvs.py) (again because it looks interesting...)
- [x] The various ivtc/dec_txt functions, and hopefully turn them into a singular function instead of a bunch of separate ones.
- [x] ~~g41fun's masked_dha~~ Added, see #76.
- [ ] Zastin's [texture mask](https://github.com/Moelancholy/Encode-Scripts/blob/b12c362cd4bf88afaceac6bba115b446a99cd798/Pizza/SSSS.Dynazenon/SSSS_Dynazenon_08.vpy#L204-L216) ([requested](https://github.com/Irrational-Encoding-Wizardry/lvsfunc/issues/74#issuecomment-929080643))

+ Other random stuff I come across that look interesting, even if not entirely functional.

Since lvsfunc is meant to be a general stop for most generic function needs, I'm always open for more requests, so if there's any older functions you feel could use adopting, please don't hesitate to leave a comment with a link here.

**Comment by Moelancholy** [comment]
Consider including Zastin's texture mask, too. It was WIP and abandoned, but it works quite well (both for general purposes for e.g. DPIR- and debandmasking with weighted merging, and for scenefiltering).

**Comment by LightArrowsEXE** [comment]
MaskedDHA has been adopted (See #76). Gonna take a look at G41Fun's other functions to see if there's anything else that's useful that could be adopted. BasedAA's adoption also done, see [commit](https://github.com/Irrational-Encoding-Wizardry/lvsfunc/commit/a00ad4fec8540a02621e2d7d8009dd012ef1d05a).

**Comment by NSQY** [comment]
A lot of functions ported from Avisynth have been outdated for years, if you have added anything to lvsfunc which was originally ported from AVS there's a good chance that there have been at least some changes (a lot of the stuff in G41Fun probably falls under this). So, if you do start adopting anything from other places please take a look.

The most active Avisynth repositories are:
https://github.com/Dogway/Avisynth-Scripts
https://gitlab.com/uvz/AviSynthPlus-Plugins-Scripts

I'm probably going to open an issue over at havsfunc so this can be discussed further.

**Comment by LightArrowsEXE** [comment]
@NSQY Sounds good. I'll do a check at some point in the future to see which of my AVS ports have been updated at some point. No guarantees I'll be able to properly update them all, simply because of the fact I find most AVS code to be nigh-unreadable, but I'll make an attempt. 👍

**Comment by LightArrowsEXE** [comment]
Add FadeFramesSimple to request list (#87)

**Comment by theChaosCoder** [comment]
The latest version of smdegrain would be nice to have in VS https://github.com/Dogway/Avisynth-Scripts/tree/master/SMDegrain%20v3.5.1d

**Comment by LightArrowsEXE** [comment]
> The latest version of smdegrain would be nice to have in VS

This is something for `vs-denoise` (which is currently in the works by another maintainer).

**Comment by theChaosCoder** [comment]
I think Inpaint was also requested a couple of times. https://github.com/pinterf/AvsInpaint

**Comment by LightArrowsEXE** [comment]
> I think Inpaint was also requested a couple of times. https://github.com/pinterf/AvsInpaint

@HolyWu said he'd be looking at porting it.

![image](https://user-images.githubusercontent.com/42927908/173242610-ceeca627-b920-4ac0-b52c-d18c2adadd7c.png)
