### ISSUE TITLE
bm3d.OPP2RGB/RGB2OPP is slower than fmtc/expr

### ISSUE THREAD

**Issue by NSQY** [Irrational-Encoding-Wizardry/lvsfunc#83]
Please see: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/issues/27

**Comment by tomato39** [comment]
not our bug, needs to be fixed in fmtc or the bm3d plugin

inlining an expr monstrosity for performance gains is not an acceptable solution
