### ISSUE TITLE
Add FadeFramesSimple

### ISSUE THREAD

**Issue by Moelancholy** [Irrational-Encoding-Wizardry/lvsfunc#87]
rfs but with fading, so that scenefiltering mid scene becomes less of a temporally inconsistent mess and pain unless you write a lot of fade_filter lines which is ugly as sin

context here: https://discord.com/channels/856381934052704266/856383302097043497/946352375206146048

**Comment by LightArrowsEXE** [comment]
This is supported in [stgfunc](https://github.com/Setsugennoao/stgfunc/blob/master/stgfunc/transitions.py#L81-L110).
